### ISSUE TITLE
Itinerary - Refactor ugly methods for searching for locations in legs

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/ddd_sample_app_ruby#14]
Remove `legs_contain_unload_location` and `legs_contain_load_location` by replacing with standard Ruby. See code comments in Itinerary. There must be a better way to do this idiomatically in Ruby. The C# code looks like:

```
   legs.Any(x => x.load_location == handling_event.location);
```

and surely there is a one-liner in Ruby. Itinerary_spec should still pass after making this change.

**Comment by mikeabiezzi** [comment]
It's basically the same as C#

`legs.any? { |leg| leg.load_location == handling_event.location }`
