### ISSUE TITLE
uninitialized constant ValueObject

### ISSUE THREAD

**Issue by silviuvoicu** [paulrayner/ddd_sample_app_ruby#59]
Hello,
I wanted to try out this application, and after I did bundle install, I try to run it with rails server but it shut's down with that error:
domain/cargo/itinerary.rb:4:in `<top (required)>': uninitialized constant ValueObject (NameError)
What I missing?
Thanks.

**Comment by paulrayner** [comment]
Major changes have been made to how value objects are implemented in the sample app, and I suspect that something got missed, causing the issue you are seeing. I'll take a look. Thanks.

**Comment by paulrayner** [comment]
Fixed with commit 74a5712.
