### ISSUE TITLE
Fix up requires for specs

### ISSUE THREAD

**Issue by paulrayner** [paulrayner/ddd_sample_app_ruby#8]
Currently have to add each model object file with an explicit require statement in the Rspec specs. Need to just be able to specify the model folder.

**Comment by drsharp** [comment]
I've somewhat fixed this. I made a single 'models_require' file. But there is still too much integration, IMO, at least for model-level tests (which ought to be straight-up unit tests of each model). Ideally, each specific model spec should only include that specific model class. Then, some other integration tests can cover across the boundaries.

**Comment by paulrayner** [comment]
Pull request #20 addresses this, though we need to uncomment the business logic specs that are now sitting in integration and rename the folder to something that doesn't imply infrastructure.
